### ISSUE TITLE
Issues creating a new network for a non-admin project

### ISSUE THREAD

**Issue by oneswig** [stackhpc/ansible-role-os-networks#1]
To create an overlay network for the use of a project, the `project` parameter must be passed to `os_network`.

However, when this is done, `shade` claims the project cannot be found.

When invoking the shade function `get_project` from the python interpreter, using the same parameters as the ansible invocation, `get_project` returns nothing unless environment variable `OS_IDENTITY_API_VERSION=3` is set.

**Comment by oneswig** [comment]
Adding this hack to the invocation of `os_network` gets things moving:
 
```
  environment:
    OS_IDENTITY_API_VERSION: 3
```

But it's not a solution.

**Comment by oneswig** [comment]
Example hack solution in https://github.com/stackhpc/ansible-role-os-networks/pull/2

**Comment by markgoddard** [comment]
In os-projects I used a variable to make it a bit more flexible:
https://github.com/stackhpc/ansible-role-os-projects/blob/master/defaults/main.yml#L12
.

**Comment by markgoddard** [comment]
Can we close this one now?

**Comment by oneswig** [comment]
Tried it again, works fine now.
