### ISSUE TITLE
Issue with enable_dhcp:false not being honoured in created openstack network

### ISSUE THREAD

**Issue by darrylweaver** [stackhpc/ansible-role-os-networks#12]
When using hpcDIRECT-config to create networks, which uses this role, the networks created do not disable DHCP when requested in the config.

e.g.:
customer_subnet_infiniband:
  name: "{{ customer_network_infiniband_name }}"
  project: "{{ customer_project_name }}"
  cidr: "192.168.94.0/24"
  allocation_pool_start: "192.168.94.1"
  allocation_pool_end: "192.168.94.254"
  enable_dhcp: no 

Also tried:
  enable_dhcp: false

**Comment by oneswig** [comment]
Quite possibly an issue with the underlying OpenStack modules in Ansible, seems familiar to me.  enable_dhcp is a parameter of os_subnet, would you be able to try invoking that module directly?  That would help subdivide the problem. 

See https://github.com/stackhpc/ansible-role-os-networks/blob/master/tasks/main.yml#L28-L46

**Comment by markgoddard** [comment]
@darrylweaver how recent is your galaxy role download? The enable_dhcp parameter was added on 13th April: https://github.com/stackhpc/ansible-role-os-networks/commit/9ca873e4ea8687cc5067d621ae693bde43739462

**Comment by darrylweaver** [comment]
Updating the galaxy role fixed the issue.
This does indicate that their is no way to be prompted if the roles are updated and out of date, the only way to automate this would be to force the download of the latest role before every run.
But for now this can be closed.
