### ISSUE TITLE
Ability to define alternative MTU for networks

### ISSUE THREAD

**Issue by oneswig** [stackhpc/ansible-role-os-networks#17]
It would be useful to be able to set the MTU on networks that have jumbo frames (or indeed frames of any non-default size).  This is supported in the Ansible module here: https://docs.ansible.com/ansible/latest/modules/os_network_module.html?highlight=mtu

**Comment by markgoddard** [comment]
I think it's only supported in the result, not as an argument.

**Comment by oneswig** [comment]
Ah, you're right, it's an output from the Ansible role.  We'd need to make a PR against the Ansible role itself to get this working.
